apiVersion: v1
kind: Service
metadata:
  name: ftps-service
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: ftps
  type: LoadBalancer
  ports:
    - name: ftps
      protocol: TCP
      port: 21
      targetPort: 21
    - name: data
      port: 20
      targetPort: 20
    - name: ftps-pasv20
      protocol: TCP
      port: 30020
      targetPort: 30020
    - name: ftps-pasv21
      protocol: TCP
      port: 30021
      targetPort: 30021

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: my_ftps
        livenessProbe:
          exec:
            command:
            - /bin/ash
            - -c
            - pgrep telegraf && pgrep vsftpd
          initialDelaySeconds: 3
          periodSeconds: 3
        imagePullPolicy: Never
        ports:
        - containerPort: 21
        - containerPort: 20
        - containerPort: 30020
        - containerPort: 30021
