apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: grafana
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: my_grafana
        livenessProbe:
          exec:
            command:
            - /bin/ash
            - -c
            - pgrep telegraf && pgrep grafana-server
          initialDelaySeconds: 3
          periodSeconds: 3
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
